import type { InferGetStaticPropsType } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getHomePageContent } from "../lib/api";

const Home = ({ test }: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>{test.name}</div>
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const data = await getHomePageContent();

  return {
    props: {
      test: data,
    },
  };
};

export default Home;
